export const STORAGE_KEYS = {
  heroes: "autochess_heroes",
  dataVersion: "autochess_data_version",
  items: "autochess_items",
  comps: "autochess_comps",
  races: "autochess_races",
  classes: "autochess_classes",
  posts: "autochess_posts",
  banners: "autochess_banners",
  relics: "autochess_relics",
  comments: "autochess_comments",
  communityPosts: "autochess_community_posts",
  teamMembers: "autochess_team_members",
  communityChannels: "autochess_community_channels",
  events: "autochess_events",
  media: "autochess_media",
  players: "autochess_players",
  adminUsers: "autochess_admin_users",
  adminRoles: "autochess_admin_roles",
} as const
