/**
 * Admin UI shell — tables, dialogs, layout helpers.
 * Import entity forms from `@/components/admin/Admin*Form` directly (lazy-load on pages).
 */
export { AdminDataTable } from "./AdminDataTable"
export { AdminFilterBar } from "./AdminFilterBar"
export { AdminPageHeader, AdminSuccessBanner, AdminDemoBadge, AdminEmptyState } from "./AdminPageHeader"
export { AdminStatCards } from "./AdminStatCards"
export { AdminDeleteDialog } from "./AdminDeleteDialog"
export { AdminTraitPanel } from "./AdminTraitPanel"
export { AdminCommentDetailDrawer } from "./AdminCommentDetailDrawer"
export { AdminTable, AdminThead, AdminTh, AdminTr, AdminTd, AdminTableScroll, AdminTableFooterText } from "./AdminTable"
export { AdminToolbar } from "./AdminToolbar"
export { AdminInlineFilter } from "./AdminInlineFilter"
export { AdminTableActionButton } from "./AdminTableActionButton"
export { AdminListShell } from "./AdminListShell"
export { AdminField, AdminFormGrid, AdminFormGridFull } from "./AdminField"
export { AdminFormDialog, AdminDetailDialog } from "./AdminFormDialog"
export type { AdminDialogSize } from "./AdminFormDialog"
export { AdminHeroDetailDialog } from "./AdminHeroDetailDialog"
export { AdminItemDetailDialog } from "./AdminItemDetailDialog"
export { AdminBannerDetailDialog } from "./AdminBannerDetailDialog"
export { AdminRelicDetailDialog } from "./AdminRelicDetailDialog"
export { AdminMediaPicker } from "./AdminMediaPicker"
export { AdminRowActions } from "./AdminRowActions"
export { AdminStatusSelect } from "./AdminStatusSelect"
export { HeroCheckboxPicker } from "./HeroCheckboxPicker"

export type { AdminUserRecord, UserFormValue } from "./AdminUserForm"
export type { BannerFormValue } from "./AdminBannerForm"
export type { CompFormValue } from "./AdminCompForm"
export type { EventFormValue } from "./AdminEventForm"
export type { TraitFormValue, TraitRecord } from "./AdminTraitForm.helpers"
export type { MediaFormValue } from "./AdminMediaForm"
export type { PlayerFormValue } from "./AdminPlayerForm"
export type { TeamFormValue } from "./AdminTeamForm"
export type { ChannelFormValue } from "./AdminChannelForm"
export type { SeoFormDraft, SeoPageMetaRow } from "./AdminSeoForm"
