// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/doi-hinh": {
    params: {};
  };
  "/doi-hinh/:id": {
    params: {
      "id": string;
    };
  };
  "/toc-he": {
    params: {};
  };
  "/toc-he/:kind/:id": {
    params: {
      "kind": string;
      "id": string;
    };
  };
  "/toc": {
    params: {};
  };
  "/toc/:id": {
    params: {
      "id": string;
    };
  };
  "/he": {
    params: {};
  };
  "/he/:id": {
    params: {
      "id": string;
    };
  };
  "/tuong": {
    params: {};
  };
  "/tuong/:id": {
    params: {
      "id": string;
    };
  };
  "/trang-bi": {
    params: {};
  };
  "/trang-bi/:id": {
    params: {
      "id": string;
    };
  };
  "/di-vat": {
    params: {};
  };
  "/di-vat/:id": {
    params: {
      "id": string;
    };
  };
  "/cong-cu/*": {
    params: {
      "*": string;
    };
  };
  "/tin-tuc": {
    params: {};
  };
  "/tin-tuc/:id": {
    params: {
      "id": string;
    };
  };
  "/bang-xep-hang": {
    params: {};
  };
  "/cong-dong": {
    params: {};
  };
  "/cong-dong/:id": {
    params: {
      "id": string;
    };
  };
  "/thao-luan": {
    params: {};
  };
  "/thao-luan/:id": {
    params: {
      "id": string;
    };
  };
  "/dang-bai": {
    params: {};
  };
  "/ho-so": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/nguoi-dung": {
    params: {};
  };
  "/admin/trang-bi": {
    params: {};
  };
  "/admin/tuong/them": {
    params: {};
  };
  "/admin/tuong/:id/sua": {
    params: {
      "id": string;
    };
  };
  "/admin/tuong": {
    params: {};
  };
  "/admin/doi-hinh": {
    params: {};
  };
  "/admin/toc-he": {
    params: {};
  };
  "/admin/toc": {
    params: {};
  };
  "/admin/he": {
    params: {};
  };
  "/admin/bai-viet": {
    params: {};
  };
  "/admin/bai-viet/them": {
    params: {};
  };
  "/admin/bai-viet/:id/sua": {
    params: {
      "id": string;
    };
  };
  "/admin/banners": {
    params: {};
  };
  "/admin/di-vat": {
    params: {};
  };
  "/admin/vai-tro": {
    params: {};
  };
  "/admin/binh-luan": {
    params: {};
  };
  "/admin/bang-xep-hang": {
    params: {};
  };
  "/admin/tin-tuc": {
    params: {};
  };
  "/admin/su-kien": {
    params: {};
  };
  "/admin/media": {
    params: {};
  };
  "/admin/bao-cao": {
    params: {};
  };
  "/admin/seo": {
    params: {};
  };
  "/admin/cai-dat": {
    params: {};
  };
  "/admin/doi-ngu": {
    params: {};
  };
  "/admin/kenh-cong-dong": {
    params: {};
  };
  "/admin/*": {
    params: {
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/robots.txt" | "/sitemap.xml" | "/doi-hinh" | "/doi-hinh/:id" | "/toc-he" | "/toc-he/:kind/:id" | "/toc" | "/toc/:id" | "/he" | "/he/:id" | "/tuong" | "/tuong/:id" | "/trang-bi" | "/trang-bi/:id" | "/di-vat" | "/di-vat/:id" | "/cong-cu/*" | "/tin-tuc" | "/tin-tuc/:id" | "/bang-xep-hang" | "/cong-dong" | "/cong-dong/:id" | "/thao-luan" | "/thao-luan/:id" | "/dang-bai" | "/ho-so" | "/admin" | "/admin/nguoi-dung" | "/admin/trang-bi" | "/admin/tuong/them" | "/admin/tuong/:id/sua" | "/admin/tuong" | "/admin/doi-hinh" | "/admin/toc-he" | "/admin/toc" | "/admin/he" | "/admin/bai-viet" | "/admin/bai-viet/them" | "/admin/bai-viet/:id/sua" | "/admin/banners" | "/admin/di-vat" | "/admin/vai-tro" | "/admin/binh-luan" | "/admin/bang-xep-hang" | "/admin/tin-tuc" | "/admin/su-kien" | "/admin/media" | "/admin/bao-cao" | "/admin/seo" | "/admin/cai-dat" | "/admin/doi-ngu" | "/admin/kenh-cong-dong" | "/admin/*" | "/*";
  };
  "routes/robots[.]txt.ts": {
    id: "routes/robots[.]txt";
    page: "/robots.txt";
  };
  "routes/sitemap[.]xml.ts": {
    id: "routes/sitemap[.]xml";
    page: "/sitemap.xml";
  };
  "routes/public-layout.tsx": {
    id: "routes/public-layout";
    page: "/" | "/doi-hinh" | "/doi-hinh/:id" | "/toc-he" | "/toc-he/:kind/:id" | "/toc" | "/toc/:id" | "/he" | "/he/:id" | "/tuong" | "/tuong/:id" | "/trang-bi" | "/trang-bi/:id" | "/di-vat" | "/di-vat/:id" | "/cong-cu/*" | "/tin-tuc" | "/tin-tuc/:id" | "/bang-xep-hang" | "/cong-dong" | "/cong-dong/:id" | "/thao-luan" | "/thao-luan/:id" | "/dang-bai" | "/ho-so";
  };
  "routes/_pages/home.tsx": {
    id: "routes/_pages/home";
    page: "/";
  };
  "routes/_pages/doi-hinh.tsx": {
    id: "routes/_pages/doi-hinh";
    page: "/doi-hinh";
  };
  "routes/_pages/doi-hinh.$id.tsx": {
    id: "routes/_pages/doi-hinh.$id";
    page: "/doi-hinh/:id";
  };
  "routes/_pages/toc-he.tsx": {
    id: "routes/_pages/toc-he";
    page: "/toc-he";
  };
  "routes/_pages/toc-he.$kind.$id.tsx": {
    id: "routes/_pages/toc-he.$kind.$id";
    page: "/toc-he/:kind/:id";
  };
  "routes/_redirects/legacy-toc-list.tsx": {
    id: "routes/_redirects/legacy-toc-list";
    page: "/toc";
  };
  "routes/_redirects/legacy-toc-detail.tsx": {
    id: "routes/_redirects/legacy-toc-detail";
    page: "/toc/:id";
  };
  "routes/_redirects/legacy-he-list.tsx": {
    id: "routes/_redirects/legacy-he-list";
    page: "/he";
  };
  "routes/_redirects/legacy-he-detail.tsx": {
    id: "routes/_redirects/legacy-he-detail";
    page: "/he/:id";
  };
  "routes/_pages/tuong.tsx": {
    id: "routes/_pages/tuong";
    page: "/tuong";
  };
  "routes/_pages/tuong.$id.tsx": {
    id: "routes/_pages/tuong.$id";
    page: "/tuong/:id";
  };
  "routes/_pages/trang-bi.tsx": {
    id: "routes/_pages/trang-bi";
    page: "/trang-bi";
  };
  "routes/_pages/trang-bi.$id.tsx": {
    id: "routes/_pages/trang-bi.$id";
    page: "/trang-bi/:id";
  };
  "routes/_pages/di-vat.tsx": {
    id: "routes/_pages/di-vat";
    page: "/di-vat";
  };
  "routes/_pages/di-vat.$id.tsx": {
    id: "routes/_pages/di-vat.$id";
    page: "/di-vat/:id";
  };
  "routes/_pages/cong-cu.tsx": {
    id: "routes/_pages/cong-cu";
    page: "/cong-cu/*";
  };
  "routes/_pages/tin-tuc.tsx": {
    id: "routes/_pages/tin-tuc";
    page: "/tin-tuc";
  };
  "routes/_pages/tin-tuc.$id.tsx": {
    id: "routes/_pages/tin-tuc.$id";
    page: "/tin-tuc/:id";
  };
  "routes/_pages/bang-xep-hang.tsx": {
    id: "routes/_pages/bang-xep-hang";
    page: "/bang-xep-hang";
  };
  "routes/_pages/cong-dong.tsx": {
    id: "routes/_pages/cong-dong";
    page: "/cong-dong";
  };
  "routes/_redirects/legacy-community-detail.tsx": {
    id: "routes/_redirects/legacy-community-detail";
    page: "/cong-dong/:id";
  };
  "routes/_pages/thao-luan.tsx": {
    id: "routes/_pages/thao-luan";
    page: "/thao-luan";
  };
  "routes/_pages/thao-luan.$id.tsx": {
    id: "routes/_pages/thao-luan.$id";
    page: "/thao-luan/:id";
  };
  "routes/_pages/dang-bai.tsx": {
    id: "routes/_pages/dang-bai";
    page: "/dang-bai";
  };
  "routes/_pages/ho-so.tsx": {
    id: "routes/_pages/ho-so";
    page: "/ho-so";
  };
  "routes/admin-layout.tsx": {
    id: "routes/admin-layout";
    page: "/admin" | "/admin/nguoi-dung" | "/admin/trang-bi" | "/admin/tuong/them" | "/admin/tuong/:id/sua" | "/admin/tuong" | "/admin/doi-hinh" | "/admin/toc-he" | "/admin/toc" | "/admin/he" | "/admin/bai-viet" | "/admin/bai-viet/them" | "/admin/bai-viet/:id/sua" | "/admin/banners" | "/admin/di-vat" | "/admin/vai-tro" | "/admin/binh-luan" | "/admin/bang-xep-hang" | "/admin/tin-tuc" | "/admin/su-kien" | "/admin/media" | "/admin/bao-cao" | "/admin/seo" | "/admin/cai-dat" | "/admin/doi-ngu" | "/admin/kenh-cong-dong" | "/admin/*";
  };
  "routes/_pages/admin-index.tsx": {
    id: "routes/_pages/admin-index";
    page: "/admin";
  };
  "routes/_pages/admin-nguoi-dung.tsx": {
    id: "routes/_pages/admin-nguoi-dung";
    page: "/admin/nguoi-dung";
  };
  "routes/_pages/admin-trang-bi.tsx": {
    id: "routes/_pages/admin-trang-bi";
    page: "/admin/trang-bi";
  };
  "routes/_pages/admin-tuong-them.tsx": {
    id: "routes/_pages/admin-tuong-them";
    page: "/admin/tuong/them";
  };
  "routes/_pages/admin-tuong-sua.tsx": {
    id: "routes/_pages/admin-tuong-sua";
    page: "/admin/tuong/:id/sua";
  };
  "routes/_pages/admin-tuong.tsx": {
    id: "routes/_pages/admin-tuong";
    page: "/admin/tuong";
  };
  "routes/_pages/admin-doi-hinh.tsx": {
    id: "routes/_pages/admin-doi-hinh";
    page: "/admin/doi-hinh";
  };
  "routes/_pages/admin-toc-he.tsx": {
    id: "routes/_pages/admin-toc-he";
    page: "/admin/toc-he";
  };
  "routes/_redirects/admin-toc.tsx": {
    id: "routes/_redirects/admin-toc";
    page: "/admin/toc";
  };
  "routes/_redirects/admin-he.tsx": {
    id: "routes/_redirects/admin-he";
    page: "/admin/he";
  };
  "routes/_pages/admin-bai-viet.tsx": {
    id: "routes/_pages/admin-bai-viet";
    page: "/admin/bai-viet";
  };
  "routes/_pages/admin-bai-viet-them.tsx": {
    id: "routes/_pages/admin-bai-viet-them";
    page: "/admin/bai-viet/them";
  };
  "routes/_pages/admin-bai-viet-sua.tsx": {
    id: "routes/_pages/admin-bai-viet-sua";
    page: "/admin/bai-viet/:id/sua";
  };
  "routes/_pages/admin-banners.tsx": {
    id: "routes/_pages/admin-banners";
    page: "/admin/banners";
  };
  "routes/_pages/admin-di-vat.tsx": {
    id: "routes/_pages/admin-di-vat";
    page: "/admin/di-vat";
  };
  "routes/_pages/admin-vai-tro.tsx": {
    id: "routes/_pages/admin-vai-tro";
    page: "/admin/vai-tro";
  };
  "routes/_pages/admin-binh-luan.tsx": {
    id: "routes/_pages/admin-binh-luan";
    page: "/admin/binh-luan";
  };
  "routes/_pages/admin-bang-xep-hang.tsx": {
    id: "routes/_pages/admin-bang-xep-hang";
    page: "/admin/bang-xep-hang";
  };
  "routes/_pages/admin-tin-tuc.tsx": {
    id: "routes/_pages/admin-tin-tuc";
    page: "/admin/tin-tuc";
  };
  "routes/_pages/admin-su-kien.tsx": {
    id: "routes/_pages/admin-su-kien";
    page: "/admin/su-kien";
  };
  "routes/_pages/admin-media.tsx": {
    id: "routes/_pages/admin-media";
    page: "/admin/media";
  };
  "routes/_pages/admin-bao-cao.tsx": {
    id: "routes/_pages/admin-bao-cao";
    page: "/admin/bao-cao";
  };
  "routes/_pages/admin-seo.tsx": {
    id: "routes/_pages/admin-seo";
    page: "/admin/seo";
  };
  "routes/_pages/admin-cai-dat.tsx": {
    id: "routes/_pages/admin-cai-dat";
    page: "/admin/cai-dat";
  };
  "routes/_pages/admin-doi-ngu.tsx": {
    id: "routes/_pages/admin-doi-ngu";
    page: "/admin/doi-ngu";
  };
  "routes/_pages/admin-kenh-cong-dong.tsx": {
    id: "routes/_pages/admin-kenh-cong-dong";
    page: "/admin/kenh-cong-dong";
  };
  "routes/_pages/admin-not-found.tsx": {
    id: "routes/_pages/admin-not-found";
    page: "/admin/*";
  };
  "routes/_redirects/catch-all.tsx": {
    id: "routes/_redirects/catch-all";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/robots[.]txt": typeof import("./src/routes/robots[.]txt.ts");
  "routes/sitemap[.]xml": typeof import("./src/routes/sitemap[.]xml.ts");
  "routes/public-layout": typeof import("./src/routes/public-layout.tsx");
  "routes/_pages/home": typeof import("./src/routes/_pages/home.tsx");
  "routes/_pages/doi-hinh": typeof import("./src/routes/_pages/doi-hinh.tsx");
  "routes/_pages/doi-hinh.$id": typeof import("./src/routes/_pages/doi-hinh.$id.tsx");
  "routes/_pages/toc-he": typeof import("./src/routes/_pages/toc-he.tsx");
  "routes/_pages/toc-he.$kind.$id": typeof import("./src/routes/_pages/toc-he.$kind.$id.tsx");
  "routes/_redirects/legacy-toc-list": typeof import("./src/routes/_redirects/legacy-toc-list.tsx");
  "routes/_redirects/legacy-toc-detail": typeof import("./src/routes/_redirects/legacy-toc-detail.tsx");
  "routes/_redirects/legacy-he-list": typeof import("./src/routes/_redirects/legacy-he-list.tsx");
  "routes/_redirects/legacy-he-detail": typeof import("./src/routes/_redirects/legacy-he-detail.tsx");
  "routes/_pages/tuong": typeof import("./src/routes/_pages/tuong.tsx");
  "routes/_pages/tuong.$id": typeof import("./src/routes/_pages/tuong.$id.tsx");
  "routes/_pages/trang-bi": typeof import("./src/routes/_pages/trang-bi.tsx");
  "routes/_pages/trang-bi.$id": typeof import("./src/routes/_pages/trang-bi.$id.tsx");
  "routes/_pages/di-vat": typeof import("./src/routes/_pages/di-vat.tsx");
  "routes/_pages/di-vat.$id": typeof import("./src/routes/_pages/di-vat.$id.tsx");
  "routes/_pages/cong-cu": typeof import("./src/routes/_pages/cong-cu.tsx");
  "routes/_pages/tin-tuc": typeof import("./src/routes/_pages/tin-tuc.tsx");
  "routes/_pages/tin-tuc.$id": typeof import("./src/routes/_pages/tin-tuc.$id.tsx");
  "routes/_pages/bang-xep-hang": typeof import("./src/routes/_pages/bang-xep-hang.tsx");
  "routes/_pages/cong-dong": typeof import("./src/routes/_pages/cong-dong.tsx");
  "routes/_redirects/legacy-community-detail": typeof import("./src/routes/_redirects/legacy-community-detail.tsx");
  "routes/_pages/thao-luan": typeof import("./src/routes/_pages/thao-luan.tsx");
  "routes/_pages/thao-luan.$id": typeof import("./src/routes/_pages/thao-luan.$id.tsx");
  "routes/_pages/dang-bai": typeof import("./src/routes/_pages/dang-bai.tsx");
  "routes/_pages/ho-so": typeof import("./src/routes/_pages/ho-so.tsx");
  "routes/admin-layout": typeof import("./src/routes/admin-layout.tsx");
  "routes/_pages/admin-index": typeof import("./src/routes/_pages/admin-index.tsx");
  "routes/_pages/admin-nguoi-dung": typeof import("./src/routes/_pages/admin-nguoi-dung.tsx");
  "routes/_pages/admin-trang-bi": typeof import("./src/routes/_pages/admin-trang-bi.tsx");
  "routes/_pages/admin-tuong-them": typeof import("./src/routes/_pages/admin-tuong-them.tsx");
  "routes/_pages/admin-tuong-sua": typeof import("./src/routes/_pages/admin-tuong-sua.tsx");
  "routes/_pages/admin-tuong": typeof import("./src/routes/_pages/admin-tuong.tsx");
  "routes/_pages/admin-doi-hinh": typeof import("./src/routes/_pages/admin-doi-hinh.tsx");
  "routes/_pages/admin-toc-he": typeof import("./src/routes/_pages/admin-toc-he.tsx");
  "routes/_redirects/admin-toc": typeof import("./src/routes/_redirects/admin-toc.tsx");
  "routes/_redirects/admin-he": typeof import("./src/routes/_redirects/admin-he.tsx");
  "routes/_pages/admin-bai-viet": typeof import("./src/routes/_pages/admin-bai-viet.tsx");
  "routes/_pages/admin-bai-viet-them": typeof import("./src/routes/_pages/admin-bai-viet-them.tsx");
  "routes/_pages/admin-bai-viet-sua": typeof import("./src/routes/_pages/admin-bai-viet-sua.tsx");
  "routes/_pages/admin-banners": typeof import("./src/routes/_pages/admin-banners.tsx");
  "routes/_pages/admin-di-vat": typeof import("./src/routes/_pages/admin-di-vat.tsx");
  "routes/_pages/admin-vai-tro": typeof import("./src/routes/_pages/admin-vai-tro.tsx");
  "routes/_pages/admin-binh-luan": typeof import("./src/routes/_pages/admin-binh-luan.tsx");
  "routes/_pages/admin-bang-xep-hang": typeof import("./src/routes/_pages/admin-bang-xep-hang.tsx");
  "routes/_pages/admin-tin-tuc": typeof import("./src/routes/_pages/admin-tin-tuc.tsx");
  "routes/_pages/admin-su-kien": typeof import("./src/routes/_pages/admin-su-kien.tsx");
  "routes/_pages/admin-media": typeof import("./src/routes/_pages/admin-media.tsx");
  "routes/_pages/admin-bao-cao": typeof import("./src/routes/_pages/admin-bao-cao.tsx");
  "routes/_pages/admin-seo": typeof import("./src/routes/_pages/admin-seo.tsx");
  "routes/_pages/admin-cai-dat": typeof import("./src/routes/_pages/admin-cai-dat.tsx");
  "routes/_pages/admin-doi-ngu": typeof import("./src/routes/_pages/admin-doi-ngu.tsx");
  "routes/_pages/admin-kenh-cong-dong": typeof import("./src/routes/_pages/admin-kenh-cong-dong.tsx");
  "routes/_pages/admin-not-found": typeof import("./src/routes/_pages/admin-not-found.tsx");
  "routes/_redirects/catch-all": typeof import("./src/routes/_redirects/catch-all.tsx");
};