import { type RouteConfig, index, layout, route } from "@react-router/dev/routes"

export default [
  route("robots.txt", "routes/robots[.]txt.ts"),
  route("sitemap.xml", "routes/sitemap[.]xml.ts"),
  layout("routes/public-layout.tsx", [
    index("routes/_pages/home.tsx"),
    route("doi-hinh", "routes/_pages/doi-hinh.tsx"),
    route("doi-hinh/:id", "routes/_pages/doi-hinh.$id.tsx"),
    route("toc-he", "routes/_pages/toc-he.tsx"),
    route("toc-he/:kind/:id", "routes/_pages/toc-he.$kind.$id.tsx"),
    route("toc", "routes/_redirects/legacy-toc-list.tsx"),
    route("toc/:id", "routes/_redirects/legacy-toc-detail.tsx"),
    route("he", "routes/_redirects/legacy-he-list.tsx"),
    route("he/:id", "routes/_redirects/legacy-he-detail.tsx"),
    route("tuong", "routes/_pages/tuong.tsx"),
    route("tuong/:id", "routes/_pages/tuong.$id.tsx"),
    route("trang-bi", "routes/_pages/trang-bi.tsx"),
    route("trang-bi/:id", "routes/_pages/trang-bi.$id.tsx"),
    route("di-vat", "routes/_pages/di-vat.tsx"),
    route("di-vat/:id", "routes/_pages/di-vat.$id.tsx"),
    route("cong-cu/*", "routes/_pages/cong-cu.tsx"),
    route("tin-tuc", "routes/_pages/tin-tuc.tsx"),
    route("tin-tuc/:id", "routes/_pages/tin-tuc.$id.tsx"),
    route("bang-xep-hang", "routes/_pages/bang-xep-hang.tsx"),
    route("cong-dong", "routes/_pages/cong-dong.tsx"),
    route("cong-dong/:id", "routes/_redirects/legacy-community-detail.tsx"),
    route("thao-luan", "routes/_pages/thao-luan.tsx"),
    route("thao-luan/:id", "routes/_pages/thao-luan.$id.tsx"),
    route("dang-bai", "routes/_pages/dang-bai.tsx"),
    route("ho-so", "routes/_pages/ho-so.tsx"),
  ]),
  route("admin", "routes/admin-layout.tsx", [
    index("routes/_pages/admin-index.tsx"),
    route("nguoi-dung", "routes/_pages/admin-nguoi-dung.tsx"),
    route("trang-bi", "routes/_pages/admin-trang-bi.tsx"),
    route("tuong/them", "routes/_pages/admin-tuong-them.tsx"),
    route("tuong/:id/sua", "routes/_pages/admin-tuong-sua.tsx"),
    route("tuong", "routes/_pages/admin-tuong.tsx"),
    route("doi-hinh", "routes/_pages/admin-doi-hinh.tsx"),
    route("toc-he", "routes/_pages/admin-toc-he.tsx"),
    route("toc", "routes/_redirects/admin-toc.tsx"),
    route("he", "routes/_redirects/admin-he.tsx"),
    route("bai-viet", "routes/_pages/admin-bai-viet.tsx"),
    route("bai-viet/them", "routes/_pages/admin-bai-viet-them.tsx"),
    route("bai-viet/:id/sua", "routes/_pages/admin-bai-viet-sua.tsx"),
    route("banners", "routes/_pages/admin-banners.tsx"),
    route("di-vat", "routes/_pages/admin-di-vat.tsx"),
    route("vai-tro", "routes/_pages/admin-vai-tro.tsx"),
    route("binh-luan", "routes/_pages/admin-binh-luan.tsx"),
    route("bang-xep-hang", "routes/_pages/admin-bang-xep-hang.tsx"),
    route("tin-tuc", "routes/_pages/admin-tin-tuc.tsx"),
    route("su-kien", "routes/_pages/admin-su-kien.tsx"),
    route("media", "routes/_pages/admin-media.tsx"),
    route("bao-cao", "routes/_pages/admin-bao-cao.tsx"),
    route("seo", "routes/_pages/admin-seo.tsx"),
    route("cai-dat", "routes/_pages/admin-cai-dat.tsx"),
    route("doi-ngu", "routes/_pages/admin-doi-ngu.tsx"),
    route("kenh-cong-dong", "routes/_pages/admin-kenh-cong-dong.tsx"),
    route("*", "routes/_pages/admin-not-found.tsx"),
  ]),
  route("*", "routes/_redirects/catch-all.tsx"),
] satisfies RouteConfig
